{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "velero-volume-controller.fullname" . }}
  labels:
    {{- include "velero-volume-controller.labels" . | nindent 4 }}
{{- end }}
