kind: pipeline
type: docker
name: default

steps:

- name: build
  image: golang:1.11
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  commands:
    - "go build -v -o release/linux/amd64/velero-volume-controller ./cmd/controller"
  when:
    event:
      - push

- name: build and push
  image: plugins/docker
  settings:
    auto_tag: true
    dockerfile: docker/Dockerfile
    password: {from_secret: docker_password}
    repo: smoothify/velero-volume-controller
    username: smoothify
  when:
    event:
      - push
      - tag