apiVersion: v2
name: velero-volume-controller
description: Kubernetes controller for velero that detects and adds relevant backup annotation to pods with volumes
type: application
version: 0.1.0
appVersion: 0.1.0
