replicaCount: 1

image:
  repository: adferrand/velero-volume-controller
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart version.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Core parameters for velero-volume-controller behavior
clusterServerCfg:
  masterURL: ""
  kubeConfig: ""
  leaseLockNamespace: velero
  leaseLockName: velero-volume-controller
veleroVolumeCfg:
  includeNamespaces: ""
  excludeNamespaces: ""
  includeVolumeTypes: persistentVolumeClaim
  excludeVolumeTypes: ""

# If true, will create the proper RBAC to watch the cluster pods
# and associate the related service account to the controller pod.
rbac:
  create: true

# If rbac.create is set to false, use serviceAccountName to associate an existing
# service account: this service account should have proper permissions to watch pods.
serviceAccountName: "default"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
