clusterServerCfg:
  masterURL:
  kubeConfig:
  leaseLockNamespace: velero
  leaseLockName: velero-volume-controller
veleroVolumeCfg:
  includeNamespaces: test
  excludeNamespaces:
  includeVolumeTypes:
  excludeVolumeTypes:
  includeClaimNames:
  excludeClaimNames:
  includeVolumeNames:
  excludeVolumeNames:
  includeStorageClasses:
  excludeStorageClasses: